apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: todo-app-deny-all
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: todo-app
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: ingress-controller
    ports:
    - protocol: TCP
      port: 3000
  egress: []
